apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-worker-config
  namespace: workload-tasks
data:
  WORKLOAD_WORKER_RUNTIME: kubernetes
  WORKLOAD_WORKER_NAME: kind-worker
  WORKLOAD_WORKER_CONCURRENCY: "1"
  WORKLOAD_WORKER_ACTION_IMAGE: workload-action:local
